FROM mysql:latest

RUN chown -R mysql:root /var/lib/mysql/

ENV MYSQL_ROOT_PASSWORD=pass
ENV MYSQL_DATABASE=appdb
ENV MYSQL_USER=mysql_user
ENV MYSQL_PASSWORD=pass
ENV MYSQL_PORT=3306
ENV MYSQL_HOST=db
