name: Deploy MultiK8s
on:
  push:
    branches:
      - main
 
env:
  SHA: $(git rev-parse HEAD)
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Test FastAPI image
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t morciu/docker-multi-py-test -f ./server/Dockerfile.dev ./server
          docker run morciu/docker-multi-py-test python -m unittest discover
 
      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
 
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-424713
 
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
 
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: asia-east1-a
 
      - name: Build
        run: |-
          docker build -t morciu/sub-frontend:latest -t morciu/sub-frontend:${{ env.SHA }} -f ./client/Dockerfile ./frontend
          docker build -t morciu/sub-server:latest -t morciu/sub-server:${{ env.SHA }} -f ./server/Dockerfile ./server
 
      - name: Push
        run: |-
          docker push morciu/sub-frontend:latest
          docker push morciu/sub-server:latest
 
          docker push morciu/sub-frontend:${{ env.SHA }}
          docker push morciu/sub-server:${{ env.SHA }}
 
      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=morciu/sub-frontend:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=morciu/sub-server:${{ env.SHA }}